# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('card', models.CharField(max_length=80)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layernumber', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=20)),
                ('payType', models.IntegerField()),
                ('payStatus', models.IntegerField()),
                ('product', models.TextField(max_length=999)),
                ('openId', models.CharField(max_length=80)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create time')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('search', models.CharField(max_length=300)),
                ('images', models.URLField()),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shelfnumber', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shopid', models.CharField(max_length=30)),
                ('remarker', models.CharField(max_length=30)),
                ('gps', models.CharField(max_length=50, unique=True)),
                ('isonline', models.IntegerField(default=1)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offset', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=30)),
                ('number', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_units', to='User.Layer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='User.Product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shelf',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelfs', to='User.Shop'),
        ),
        migrations.AddField(
            model_name='layer',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_layers', to='User.Shelf'),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Company'),
        ),
    ]
